name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install Gleam
        run: |
          curl -sSL https://raw.githubusercontent.com/gleam-lang/gleam/main/install.sh | sh
        if: matrix.platform != 'windows-latest'
        
      - name: Install Gleam (Windows)
        run: |
          iwr https://github.com/gleam-lang/gleam/releases/download/v0.32.0/gleam-v0.32.0-windows-x86_64.zip -OutFile gleam.zip
          Expand-Archive -Path gleam.zip -DestinationPath .
          Move-Item -Path .\gleam.exe -Destination $env:USERPROFILE\.cargo\bin\gleam.exe
        if: matrix.platform == 'windows-latest'

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build Gleam
        run: npm run build:gleam
        
      - name: Build frontend
        run: npm run build
      
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install frontend dependencies
        run: npm install
      
      - name: Lint TypeScript
        run: npx tsc --noEmit
      
      - name: Lint Rust
        run: |
          cd src-tauri
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
